# Generated by Django 2.2.3 on 2019-10-29 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20191029_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='good',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.Good'),
        ),
    ]
