# Generated by Django 2.2.3 on 2019-11-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20191120_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='aptmt',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
