# Generated by Django 2.2.3 on 2019-12-06 09:24

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20191122_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to='shop/%Y/%m/%d', verbose_name='Image'),
        ),
    ]
