# Generated by Django 2.2.3 on 2020-01-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_galcat_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='galcat',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
